const express = require("express");
const cors = require("cors");
const mysql = require("mysql2/promise");
const client = require("prom-client");
const app = express(); const PORT = process.env.PORT || 3000;
app.use(cors()); app.use(express.json()); client.collectDefaultMetrics();
const requests = new client.Counter({ name: "review_service_http_requests_total", help: "Total HTTP requests", labelNames: ["method", "path", "status"] });
app.use((req, res, next) => { res.on("finish", () => requests.inc({ method: req.method, path: req.path, status: String(res.statusCode) })); next(); });
const pool = mysql.createPool({ host: process.env.MYSQL_HOST || "mysql", user: process.env.MYSQL_USER || "root", password: process.env.MYSQL_PASSWORD || "root123", database: "review_db", waitForConnections: true, connectionLimit: 10 });
app.get("/health", (req, res) => res.json({ service: "review-service", status: "ok" }));
app.get("/ready", async (req, res) => { try { await pool.query("SELECT 1"); res.json({ ready: true }); } catch (e) { res.status(500).json({ ready: false, error: e.message }); } });
app.get("/metrics", async (req, res) => { res.set("Content-Type", client.register.contentType); res.end(await client.register.metrics()); });
app.post("/reviews", async (req, res) => { const { productId, userId, rating, comment } = req.body; const [result] = await pool.execute("INSERT INTO reviews (product_id, user_id, rating, comment) VALUES (?, ?, ?, ?)", [productId, userId, rating, comment]); res.status(201).json({ id: result.insertId, productId, userId, rating, comment }); });
app.get("/reviews/product/:productId", async (req, res) => { const [rows] = await pool.execute("SELECT * FROM reviews WHERE product_id = ? ORDER BY id DESC", [req.params.productId]); res.json(rows); });
app.listen(PORT, () => console.log(`review-service running on ${PORT}`));
