import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

function App() {
  const [products, setProducts] = useState([]);
  const [cart, setCart] = useState([]);
  const [orders, setOrders] = useState([]);
  const [notifications, setNotifications] = useState([]);
  const [reviews, setReviews] = useState([]);
  const [stock, setStock] = useState({});
  const [user, setUser] = useState(null);
  const [activePage, setActivePage] = useState("home");
  const [activeCategory, setActiveCategory] = useState("All");
  const [searchTerm, setSearchTerm] = useState("");
  const [message, setMessage] = useState("");
  const [cartOpen, setCartOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [orderSuccess, setOrderSuccess] = useState(null);
  const fallbackImage = "https://dummyimage.com/700x450/e8f0fe/111827&text=Product+Image";
  const [form, setForm] = useState({ name: "pravallika", email: "pravallika@example.com", password: "password123", cardNumber: "1111", review: "Excellent product" });
  const [newProduct, setNewProduct] = useState({ name: "iPhone 15 Pro", description: "Premium Apple smartphone with powerful camera", category: "Mobiles", price: "129999", image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=80" });

  async function api(path, options = {}) {
    const res = await fetch(`/api${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) }, body: options.body ? JSON.stringify(options.body) : undefined });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(data.error || data.detail || "API failed");
    return data;
  }
  function flash(text) { setMessage(typeof text === "string" ? text : JSON.stringify(text)); setTimeout(() => setMessage(""), 4000); }
  function price(value) { return Number(value || 0).toLocaleString("en-IN"); }
  function getCategory(product) { if (product.category) return product.category; const name = String(product.name || "").toLowerCase(); if (name.includes("laptop")) return "Laptops"; if (name.includes("mobile") || name.includes("phone") || name.includes("iphone") || name.includes("samsung")) return "Mobiles"; if (name.includes("mouse") || name.includes("keyboard") || name.includes("headphone") || name.includes("accessory") || name.includes("charger") || name.includes("cable")) return "Accessories"; return "Electronics"; }
  const enrichedProducts = useMemo(() => products.map(p => ({ ...p, category: getCategory(p), rating: "4.3", ratings: "1,245", discount: "15% off" })), [products]);
  const filteredProducts = useMemo(() => enrichedProducts.filter(p => (activeCategory === "All" || p.category === activeCategory) && (!searchTerm.trim() || `${p.name} ${p.description} ${p.category}`.toLowerCase().includes(searchTerm.trim().toLowerCase()))), [enrichedProducts, activeCategory, searchTerm]);
  const cartCount = cart.reduce((sum, item) => sum + Number(item.quantity), 0);
  const cartTotal = cart.reduce((sum, item) => sum + Number(item.price) * Number(item.quantity), 0);

  async function loadProducts() { try { setProducts(await api("/products")); flash("Products loaded from Product Service"); } catch (e) { flash(e.message); } }
  async function register() { try { const data = await api("/auth/register", { method: "POST", body: { name: form.name, email: form.email, password: form.password } }); setUser(data.user); flash("Account created successfully"); setActivePage("home"); } catch (e) { flash(e.message); } }
  async function login() { try { const data = await api("/auth/login", { method: "POST", body: { email: form.email, password: form.password } }); setUser(data.user); flash("Logged in successfully"); loadCart(data.user.id); loadOrders(data.user.id); setActivePage("home"); } catch (e) { flash(e.message); } }
  function logout() { setUser(null); setCart([]); setOrders([]); flash("Logged out successfully"); setActivePage("home"); }
  async function checkStock(productId) { try { const data = await api(`/inventory/${productId}`); setStock(prev => ({ ...prev, [productId]: data.quantity })); flash(`Stock available: ${data.quantity}`); } catch (e) { flash(e.message); } }
  async function addToCart(product, openCart = false) { if (!user) { flash("Please login before adding items to cart"); setActivePage("account"); return; } try { const data = await api("/cart/add", { method: "POST", body: { userId: user.id, productId: product.id, name: product.name, price: product.price, quantity: 1 } }); setCart(data); flash(`${product.name} added to cart`); if (openCart) setCartOpen(true); } catch (e) { flash(e.message); } }
  async function loadCart(userId = user?.id) { if (!userId) { flash("Please login to view cart"); return; } try { setCart(await api(`/cart/${userId}`)); flash("Cart loaded from Redis"); } catch (e) { flash(e.message); } }
  async function clearCart() { if (!user) return; try { await api("/cart/clear", { method: "POST", body: { userId: user.id } }); setCart([]); flash("Cart cleared"); } catch (e) { flash(e.message); } }
  async function checkout() { if (!user) { flash("Please login first"); setActivePage("account"); return; } if (cart.length === 0) { flash("Your cart is empty"); return; } try { const data = await api("/orders", { method: "POST", body: { userId: user.id, items: cart, cardNumber: form.cardNumber } }); await api("/cart/clear", { method: "POST", body: { userId: user.id } }); setCart([]); setOrderSuccess(data); setCartOpen(false); setActivePage("success"); loadOrders(user.id); loadNotifications(); flash(`Order placed successfully. Order ID: ${data.orderId}`); } catch (e) { flash(e.message); } }
  async function loadOrders(userId = user?.id) { if (!userId) return; try { setOrders(await api(`/orders/${userId}`)); } catch (e) { flash(e.message); } }
  async function loadNotifications() { try { setNotifications(await api("/notifications")); } catch (e) { console.log(e.message); } }
  async function addReview(productId) { if (!user) { flash("Please login before adding review"); setActivePage("account"); return; } try { await api("/reviews", { method: "POST", body: { productId, userId: user.id, rating: 5, comment: form.review } }); flash("Review added successfully"); loadReviews(productId); } catch (e) { flash(e.message); } }
  async function loadReviews(productId) { try { setReviews(await api(`/reviews/product/${productId}`)); setActivePage("reviews"); } catch (e) { flash(e.message); } }
  async function addProduct() { try { const product = await api("/products", { method: "POST", body: { name: newProduct.name, description: newProduct.description, category: newProduct.category, price: Number(newProduct.price), image_url: newProduct.image_url } }); await api("/inventory/upsert", { method: "POST", body: { productId: product.id, quantity: 50 } }); flash("New product and stock added successfully"); await loadProducts(); setActiveCategory(newProduct.category); setActivePage("products"); } catch (e) { flash(e.message); } }
  function openCategory(category) { setActiveCategory(category); setActivePage("products"); }
  function openHome() { setActiveCategory("All"); setSearchTerm(""); setActivePage("home"); }
  useEffect(() => { loadProducts(); loadNotifications(); }, []);

  return <div className="premium-app">
    <header className="premium-header"><div className="brand-area" onClick={openHome}><div className="brand-logo">🛒</div><div><h1>CloudCart</h1><p>Designed by Pravallika</p></div></div><div className="search-area"><input placeholder="Search for mobiles, laptops, accessories and more" value={searchTerm} onChange={e => { setSearchTerm(e.target.value); setActivePage("products"); }} /><button onClick={() => setActivePage("products")}>Search</button></div><div className="header-actions"><button onClick={() => setActivePage("account")}>{user ? `Hi, ${user.name}` : "Login"}</button><button onClick={() => setActivePage("orders")}>Orders</button><button className="cart-action" onClick={() => setCartOpen(true)}>Cart <span>{cartCount}</span></button></div></header>
    <nav className="premium-nav"><button onClick={openHome}>Home</button><button onClick={() => openCategory("Electronics")}>Electronics</button><button onClick={() => openCategory("Mobiles")}>Mobiles</button><button onClick={() => openCategory("Laptops")}>Laptops</button><button onClick={() => openCategory("Accessories")}>Accessories</button><button onClick={() => setActivePage("deals")}>Today Deals</button><button onClick={() => setActivePage("admin")}>Admin</button><button onClick={() => setActivePage("project")}>Project</button></nav>
    {message && <div className="toast">{message}</div>}
    <main className="premium-main">
      {activePage === "home" && <><section className="hero-premium"><div className="hero-left"><span className="eyebrow">pravallika Microservices Project</span><h2>Premium CloudCart E-Commerce Platform</h2><p>A real-time full-stack microservices project with React, API Gateway, Auth, Product, Inventory, Cart, Order, Payment, Shipping, Notification and Review services.</p><div className="hero-cta"><button onClick={() => setActivePage("products")}>Start Shopping</button><button className="outline-btn" onClick={() => setActivePage("project")}>View Architecture</button></div><div className="tech-tags"><span>React</span><span>Node.js</span><span>MySQL</span><span>Redis</span><span>Kubernetes</span><span>Prometheus</span></div></div><div className="hero-right"><div className="deal-card big"><p>Featured Deal</p><h3>Laptop Pro 15</h3><strong>₹89,999</strong><span>Free delivery + 15% off</span></div><div className="mini-deals"><div><p>Accessories</p><strong>From ₹1,499</strong></div><div><p>Cloud Native</p><strong>10+ Services</strong></div></div></div></section><section className="category-tiles"><div onClick={() => openCategory("Mobiles")}><span>📱</span><h3>Mobiles</h3><p>Smartphones and gadgets</p></div><div onClick={() => openCategory("Laptops")}><span>💻</span><h3>Laptops</h3><p>Developer-ready laptops</p></div><div onClick={() => openCategory("Accessories")}><span>🎧</span><h3>Accessories</h3><p>Keyboard, mouse, headphones</p></div><div onClick={() => setActivePage("project")}><span>☸️</span><h3>DevOps Project</h3><p>Kubernetes microservices</p></div></section><section className="stats-grid"><div className="stat-box"><h3>10+</h3><p>Microservices</p></div><div className="stat-box"><h3>{products.length}</h3><p>Products</p></div><div className="stat-box"><h3>{cartCount}</h3><p>Cart Items</p></div><div className="stat-box"><h3>{orders.length}</h3><p>Orders</p></div></section><section className="owner-banner"><div><h3>Designed by Pravallika</h3><p>CloudCart is a real-time DevOps + Development training project built to demonstrate production-style microservices on Kubernetes.</p></div><button onClick={() => setActivePage("project")}>Explore Project</button></section></>}
      {(activePage === "home" || activePage === "products" || activePage === "deals") && <section className="premium-card"><div className="section-heading"><div><h2>{activePage === "deals" ? "Today Deals" : activeCategory === "All" ? "Recommended Products" : `${activeCategory} Products`}</h2><p>Product cards are powered by Product Service, Inventory Service, Cart Service and Redis.</p></div><div className="heading-actions"><span>{filteredProducts.length} items</span><button onClick={loadProducts}>Reload Products</button></div></div><div className="filter-tabs">{["All", "Electronics", "Mobiles", "Laptops", "Accessories"].map(cat => <button key={cat} className={activeCategory === cat ? "active" : ""} onClick={() => setActiveCategory(cat)}>{cat}</button>)}</div>{filteredProducts.length === 0 ? <div className="empty-screen"><h3>No products found</h3><p>No products are available for <strong>{activeCategory}</strong>. Add products from the Admin page.</p><button onClick={() => setActivePage("admin")}>Add Product</button></div> : <div className="product-grid-premium">{filteredProducts.map(product => <article className="premium-product" key={product.id}><div className="product-img-box"><img src={product.image_url || fallbackImage} alt={product.name} onError={e => { e.currentTarget.src = fallbackImage; }} /><span className="product-ribbon">Pravallika Choice</span><button className="quick-view" onClick={() => setSelectedProduct(product)}>Quick View</button></div><div className="product-data"><span className="product-category">{product.category}</span><h3>{product.name}</h3><p>{product.description}</p><div className="rating-line"><span>{product.rating} ★</span><small>{product.ratings} ratings</small></div><div className="price-area"><strong>₹{price(product.price)}</strong><small>{product.discount}</small></div><p className="delivery">Free delivery by tomorrow</p><div className="stock-status">Stock: {stock[product.id] ?? "Click check stock"}</div><div className="product-buttons"><button onClick={() => checkStock(product.id)}>Stock</button><button className="buy-btn" onClick={() => addToCart(product, true)}>Add Cart</button></div><div className="text-links"><button onClick={() => setSelectedProduct(product)}>Details</button><button onClick={() => loadReviews(product.id)}>Reviews</button></div></div></article>)}</div>}</section>}
      {activePage === "account" && <section className="premium-card two-col"><div className="login-box"><span className="eyebrow dark">Auth Service</span><h2>Login or Create Account</h2><p>This page is connected to Auth Service and stores users in MySQL.</p><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Full Name" /><input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Email" /><input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Password" /><div className="form-buttons"><button className="buy-btn" onClick={register}>Register</button><button onClick={login}>Login</button>{user && <button className="danger" onClick={logout}>Logout</button>}</div></div><div className="profile-card"><h3>Profile</h3>{user ? <><div className="avatar">{user.name?.charAt(0)}</div><p><strong>Name:</strong> {user.name}</p><p><strong>Email:</strong> {user.email}</p><p><strong>Role:</strong> {user.role}</p><p><strong>Project:</strong> Pravallika Microservices Project</p></> : <div className="empty-mini"><h4>No user logged in</h4><p>Login to add cart items and place orders.</p></div>}</div></section>}
      {activePage === "orders" && <section className="premium-card"><div className="section-heading"><div><h2>My Orders</h2><p>Order Service communicates with Inventory, Payment, Shipping and Notification services.</p></div><button onClick={() => loadOrders()}>Reload Orders</button></div>{orders.length === 0 ? <div className="empty-screen"><h3>No orders yet</h3><p>Add products to cart and place your first order.</p><button onClick={() => setActivePage("products")}>Shop Now</button></div> : <div className="list-grid">{orders.map(order => <div className="order-card" key={order.id}><div><h3>Order #{order.id}</h3><p>Status: {order.status}</p><small>Created by Order Service</small></div><strong>₹{price(order.total_amount)}</strong></div>)}</div>}</section>}
      {activePage === "success" && <section className="success-screen"><div className="success-icon">✅</div><h2>Order Placed Successfully</h2><p>Your order has been created using Order, Payment, Shipping and Notification services.</p>{orderSuccess && <div className="success-details"><p><strong>Order ID:</strong> {orderSuccess.orderId}</p><p><strong>Status:</strong> {orderSuccess.status}</p><p><strong>Total:</strong> ₹{price(orderSuccess.total)}</p></div>}<button onClick={() => setActivePage("orders")}>View Orders</button></section>}
      {activePage === "notifications" && <section className="premium-card"><div className="section-heading"><div><h2>Notifications</h2><p>Notification Service stores platform messages in MySQL.</p></div><button onClick={loadNotifications}>Reload</button></div>{notifications.length === 0 ? <div className="empty-screen"><h3>No notifications</h3><p>Place an order to generate notifications.</p></div> : <div className="list-grid">{notifications.map(n => <div className="notification-card" key={n.id}><h3>{n.type}</h3><p>{n.message}</p></div>)}</div>}</section>}
      {activePage === "reviews" && <section className="premium-card"><div className="section-heading"><div><h2>Product Reviews</h2><p>Review Service stores product reviews in MySQL.</p></div></div><input value={form.review} onChange={e => setForm({ ...form, review: e.target.value })} placeholder="Write review text" />{reviews.length === 0 ? <div className="empty-screen"><h3>No reviews loaded</h3><p>Click Reviews on a product card to load reviews.</p></div> : <div className="list-grid">{reviews.map(r => <div className="review-card" key={r.id}><h3>Product {r.product_id}</h3><p>Rating: {r.rating}/5</p><p>{r.comment}</p></div>)}</div>}</section>}
      {activePage === "admin" && <section className="premium-card two-col"><div className="login-box"><span className="eyebrow dark">Admin Product Service</span><h2>Add New Product</h2><p>This form creates product in MySQL and stock in Inventory Service.</p><input value={newProduct.name} onChange={e => setNewProduct({ ...newProduct, name: e.target.value })} placeholder="Product Name" /><input value={newProduct.description} onChange={e => setNewProduct({ ...newProduct, description: e.target.value })} placeholder="Product Description" /><select value={newProduct.category} onChange={e => setNewProduct({ ...newProduct, category: e.target.value })}><option value="Electronics">Electronics</option><option value="Mobiles">Mobiles</option><option value="Laptops">Laptops</option><option value="Accessories">Accessories</option></select><input value={newProduct.price} onChange={e => setNewProduct({ ...newProduct, price: e.target.value })} placeholder="Price" /><input value={newProduct.image_url} onChange={e => setNewProduct({ ...newProduct, image_url: e.target.value })} placeholder="Image URL" /><button className="buy-btn full" onClick={addProduct}>Add Product</button></div><div className="admin-preview"><h3>Product Preview</h3><img src={newProduct.image_url || fallbackImage} alt={newProduct.name} onError={e => { e.currentTarget.src = fallbackImage; }} /><span className="product-category">{newProduct.category}</span><h2>{newProduct.name}</h2><p>{newProduct.description}</p><strong>₹{price(newProduct.price)}</strong></div></section>}
      {activePage === "project" && <section className="premium-card"><span className="eyebrow dark">Designed by Pravallika</span><h2>CloudCart Microservices Architecture</h2><p className="project-intro">This project is designed as a real-time full-stack DevOps and microservices training platform. It shows how a frontend connects to an API Gateway, which routes traffic to multiple backend microservices deployed on Kubernetes.</p><div className="architecture-box"><div>React Frontend</div><span>→</span><div>NGINX Ingress</div><span>→</span><div>API Gateway</div><span>→</span><div>Microservices</div><span>→</span><div>MySQL / Redis</div></div><div className="project-grid"><div><h3>Frontend</h3><p>React premium e-commerce UI with category pages, cart drawer and admin page.</p></div><div><h3>Backend</h3><p>Auth, Product, Inventory, Cart, Order, Payment, Shipping, Notification and Review services.</p></div><div><h3>Database</h3><p>MySQL databases for service data and Redis for cart/cache use cases.</p></div><div><h3>DevOps</h3><p>Kubernetes, Ingress, Docker images, Prometheus, Grafana and alerting-ready metrics.</p></div></div><div className="signature-card"><h2>Pravallika Microservices Project</h2><p>Cloud | DevOps | Kubernetes | AIOps | Microservices | Real-Time Training</p></div></section>}
    </main>
    {cartOpen && <div className="cart-overlay"><div className="cart-drawer"><div className="drawer-header"><h2>My Cart</h2><button onClick={() => setCartOpen(false)}>✕</button></div>{cart.length === 0 ? <div className="empty-screen small"><h3>Your cart is empty</h3><p>Add products to continue.</p><button onClick={() => { setCartOpen(false); setActivePage("products"); }}>Shop Products</button></div> : <><div className="drawer-items">{cart.map((item, i) => <div className="drawer-item" key={i}><div><h3>{item.name}</h3><p>Qty: {item.quantity}</p></div><strong>₹{price(Number(item.price) * Number(item.quantity))}</strong></div>)}</div><div className="drawer-summary"><p>Total Items: {cartCount}</p><h2>₹{price(cartTotal)}</h2><input value={form.cardNumber} onChange={e => setForm({ ...form, cardNumber: e.target.value })} placeholder="Card number" /><small>Use 1111 for success, 0000 for failed payment</small><button className="buy-btn full" onClick={checkout}>Place Order</button><button className="clear-btn full" onClick={clearCart}>Clear Cart</button></div></>}</div></div>}
    {selectedProduct && <div className="modal-overlay"><div className="product-modal"><button className="modal-close" onClick={() => setSelectedProduct(null)}>✕</button><div className="modal-image"><img src={selectedProduct.image_url || fallbackImage} alt={selectedProduct.name} onError={e => { e.currentTarget.src = fallbackImage; }} /></div><div className="modal-info"><span className="product-category">{selectedProduct.category}</span><h2>{selectedProduct.name}</h2><p>{selectedProduct.description}</p><div className="rating-line"><span>4.3 ★</span><small>1,245 ratings</small></div><div className="price-area large"><strong>₹{price(selectedProduct.price)}</strong><small>15% off</small></div><p className="delivery">Free delivery by tomorrow</p><div className="stock-status">Stock: {stock[selectedProduct.id] ?? "Click check stock"}</div><div className="product-buttons"><button onClick={() => checkStock(selectedProduct.id)}>Check Stock</button><button className="buy-btn" onClick={() => addToCart(selectedProduct, true)}>Add to Cart</button></div><button className="review-btn" onClick={() => addReview(selectedProduct.id)}>Add Review</button></div></div></div>}
    <footer className="premium-footer"><div><h2>CloudCart</h2><p>Designed by Pravallika</p></div><div><p>React + Node.js + API Gateway + MySQL + Redis + Kubernetes</p><p>Production-style E-Commerce Microservices Project</p></div></footer>
  </div>;
}

createRoot(document.getElementById("root")).render(<App />);
